# Tensorflow Basics

# Getting Started

TensorFlow is an open source software library created by Google that is used to implement machine learning and deep learning systems. These two names contain a series of powerful algorithms that share a common challenge—to allow a computer to learn how to automatically spot complex patterns and/or to make best possible decisions.

TensorFlow is a library for numerical computation where data flows through the graph.  Data in TensorFlow is represented by n-dimensional arrays called Tensors. Graph is made of data(Tensors) and mathematical operations. 

* Nodes on the graph: represent mathematical operations. 
* Edges on the graph: represent the Tensors that flow between operations. 

In [4]:
import warnings
warnings.filterwarnings('ignore', '.*do not.*',)

There is one more aspect in which TensorFlow is very different from any other programming language. In TensorFlow, you first need to create a blueprint of whatever you want to create. While you are creating the graph, variables don’t have any value. Later when you have created the complete graph, you have to run it inside a session, only then the variables have any values. More on this later. 

# Graph in TensorFlow:

Graph is the backbone of TensorFlow and every computation/operation/variables reside on the graph. Everything that happens in the code, resides on a default graph provided by TensorFlow. We can access this graph by:

In [9]:
#tensorflow import
import tensorflow as tf

graph = tf.get_default_graph()

We can get the list of all the operations by typing this

In [10]:
graph.get_operations()

[<tf.Operation 'Const' type=Const>]

Currently, the output is empty as shown by [], as there is nothing in the graph.
If we want to print to name of the operations in the graph, do this:

In [11]:
for op in graph.get_operations(): 
    print(op.name)

Const


This will again be empty. We shall use this to print names of operations after we have added ops to the graph.

Also, It’s possible to create multiple graphs.

# Constants:

TF holds data in Tensors which are similar to numPy multi-dimensional arrays(although they are different from numPy Arrays):

* Constants are constants whose value can’t be changed. We can declare a constant like this: 

In [12]:
#tensorflow import
import tensorflow as tf

In [13]:
a=tf.constant(1.0)

In [14]:
a

<tf.Tensor 'Const_1:0' shape=() dtype=float32>

As we can see, this is different from other programming languages like python, we can’t print/access constant a unless we run it inside a session. So*** what is a session ?***

In [17]:
with tf.Session() as sess:
    print(sess.run(a))

1.0


# TensorFlow Session:

A graph is used to define operations, but the operations are only run within a session. Graphs and sessions are created independently of each other. We can imagine graph to be similar to a blueprint, and a session to be similar to a construction site.

Graph only defines the computations or builds the blueprint. However, there are no variables, no values unless we run the graph or part of the graph within a session.

Whenever, we open a session, we need to remember to close it. Or we can use ‘with block’ like this.

In [ ]:
with tf.Session() as sess:
    sess.run(f)

Advantage of with block is: session closes automatically at the end of the with block.

# Variables

Variables are again Tensors which are like variables in any other language. 

In [18]:
b = tf.Variable(2.0,name="test_var")

In [19]:
b

<tf.Variable 'test_var:0' shape=() dtype=float32_ref>

Variables(as you can guess by the name) can hold different values as opposed to constants. However, they need to be separately initialized by an init op. It could be taxing to initialize all the variables individually. However, TensorFlow provides a mechanism to initialize all the variables in one go. Let’s see how to do that:

In [22]:
init_op = tf.global_variables_initializer()

This will add init_op to our tensorflow default graph.
Now we run this init_op before we try to access your variable:

In [23]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(b))

2.0


Now,we will try to print the operations on the graph: 

In [24]:
graph = tf.get_default_graph()
for op in graph.get_operations(): 
    print(op.name)

Const
Const_1
test_var/initial_value
test_var
test_var/Assign
test_var/read
init
init_1


As you can see, we have declared ‘a’ as Const so this has been added to the graph. Similarly, for the variable b, many ‘test_var’ states have been added to the TensorFlow graph like test_var/initial_value, test_var/read etc. We can visualize the complete network using TensorBoard, which is a tool to visualize a TensorFlow graph and training process.

*** More On Variables ***

In [25]:
#A basic Python Script

x = 35
y = x + 5
print(y)

40


This script basically just says “create a variable x with value 35, set the value of a new variable y to that plus 5, which is currently 40, and print it out”. The value 40 will print out when we run this program.

***let’s convert it to a TensorFlow equivalent.***

In [26]:
import tensorflow as tf

x = tf.constant(35,name='x')
y = tf.Variable(x+5,name='y')

print(y)

<tf.Variable 'y:0' shape=() dtype=int32_ref>


The code here does the following:

1. Import the tensorflow module and call it tf
2. Create a constant value called x, and give it the numerical value 35
3. Create a Variable called y, and define it as being the equation x + 5
4. Print out the equation object for y

The subtle difference is that y isn’t given “the current value of x + 5” as in our previous program. Instead, it is effectively an equation that means “when this variable is computed, take the value of x (as it is then) and add 5 to it”. The computation of the value of y is never actually performed in the above program.

Let’s fix that

In [29]:
import tensorflow as tf

x = tf.constant(35,name='x')
y = tf.Variable(x+5,name='y')

model = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(model)
    print(session.run(y))

40


We have removed the print(y) statement, and instead we have code that creates a session, and actually computes the value of y. This is quite a bit of boilerplate, but it works like this:

1. Import the tensorflow module and call it tf
2. Create a constant value called x, and give it the numerical value 35
3. Create a Variable called y, and define it as being the equation x + 5
4. Initialize the variables with tf.global_variables_initializer() 
5. Create a session for computing the values
6. Run the model created in 4
7. Run just the variable y and print out its current value

The step 4 above is where some magic happens. In this step, a graph is created of the dependencies between the variables. In this case, the variable y depends on the variable x, and that value is transformed by adding 5 to it.Lets Keep in mind that this value isn’t computed until step 7, as up until then, only equations and relations are computed.

In [41]:
#Simple Example

In [42]:
import tensorflow as tf


x = tf.constant([35, 40, 45], name='x')
y = tf.Variable(x + 5, name='y')


model = tf.global_variables_initializer()

with tf.Session() as session:
	session.run(model)
	print(session.run(y))

[40 45 50]


# Placeholders

So far we have used Variables to manage our data, but there is a more basic structure, the placeholder. A placeholder is simply a variable that we will assign data to at a later date. It allows us to create our operations and build our computation graph, without needing the data. In TensorFlow terminology, we then feed data into the graph through these placeholders.

OR

Placeholders are tensors which are waiting to be initialized/fed. Placeholders are used for training data which is only fed when the code is actually run inside a session. What is fed to Placeholder is called feed_dict. Feed_dict are key value pairs for holding data:

In [43]:
a = tf.placeholder("float")

In [44]:
b = tf.placeholder("float")

In [45]:
y = tf.multiply(a, b)

In [46]:
#Typically we load feed_dict from somewhere else, 
#may be reading from a training data folder. etc
#For simplicity, we have put values in feed_dict here

feed_dict ={a:2,b:3}

In [47]:
with tf.Session() as sess:
       print(sess.run(y,feed_dict))

6.0


*** Detailed Explanation ***

In [48]:
import tensorflow as tf

x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

[2. 4. 6.]


***  let’s break it down. ***

First, we import tensorflow as normal. Then we create a placeholder called x, i.e. a place in memory where we will store value later on.

Then, we create a Tensor called, which is the operation of multiplying x by 2. Note that we haven’t defined any initial values for x yet.

We now have an operation (y) defined, and can now run it in a session. We create a session object, and then run just the y variable. Note that this means, that if we defined a much larger graph of operations, we can run just a small segment of the graph. This subgraph evaluation is actually a bit selling point of TensorFlow, and one that isn’t present in many other libraries that do similar things.

Running y requires knowledge about the values of x. We define these inside the feed_dict argument to run. We state here that the values of x are [1, 2, 3]. We run y, giving us the result of [2, 4, 6].

Placeholders do not need to be statically sized. Let’s update our program to allow x to take on any length. Change the definition of x to be:

In [49]:
x = tf.placeholder("float", None)

Now, when we define the values of x in the feed_dict we can have any number of values. The code should still work, and give the same answer, but now it will also work with any number of values in feed_dict.

Placeholders can also have multiple dimensions, allowing for storing arrays. In the following example, we create a 3 by 2 matrix, and store some numbers in it. We then use the same operation as before to do element-wise doubling of the numbers.

In [50]:
import tensorflow as tf

x = tf.placeholder("float", [None, 3])
y = x * 2

In [51]:
with tf.Session() as session:
    x_data = [[1, 2, 3],
              [4, 5, 6],]
    result = session.run(y, feed_dict={x: x_data})
    print(result)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]


The first dimension of the placeholder is None, meaning we can have any number of rows. The second dimension is fixed at 3, meaning each row needs to have three columns of data.

# Interactive Sessions

Now that we have a few examples under our belt, let us take a look at what is happening a bit more closely.

As we have identified earlier, TensorFlow allows us to create a graph of operations and variables. These variables are called Tensors, and represent data, whether that is a single number, a string, a matrix, or something else. Tensors are combined through operations, and this whole process is modelled in a graph.

Next, as before, let’s create a basic TensorFlow program. One major change is the use of an InteractiveSession, which allows us to run variables without needing to constantly refer to the session object (less typing!). Code blocks below are broken into different cells. If we see a break in the code, we will need to run the previous cell first. Also, if we aren’t otherwise confident, ensure all of the code in a given block is type into a cell before we run it.

In [52]:
import tensorflow as tf

session = tf.InteractiveSession()

x = tf.constant(list(range(10)))

In this section of code, we create an InteractiveSession, and then define a constant value, which is like a placeholder, but with a set value (that doesn’t change). In the next cell, we can evaluate this constant and print the result.

In [53]:
print(x.eval())

[0 1 2 3 4 5 6 7 8 9]


In [54]:
#Next, we close the open session.
session.close()

Closing sessions is quite important, and can be easy to forget. For that reason, we were using the with keyword in earlier tutorials to handle this. When the with block is finished executing, the session will be closed (this also happens if an error happens - the session is still closed).