# PyTorch Fundamentals

## Matrix Basics

***Matrices Brief Introduction ***

* Basic Defination: rectangular array of numbers
* Tensors(PyTorch)
* Ndarrays(Numpy)

### 1. Creating matrix

In [1]:
import numpy as np

In [2]:
# creating a 2*2 matrix using python

arr = [[1,2],[3,4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
#convert to numpy 

np.array(arr)



array([[1, 2],
       [3, 4]])

In [4]:
#in pytorch

import torch

In [5]:
#converting to PyTorch Tensor 

torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

### 2. Creating Matrices with Default Values

In [7]:
#using numpy

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
#using torch
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [9]:
#generating random number using numpy
np.random.randn(2,2)

array([[-1.13263105, -0.03667296],
       [ 0.38527848,  0.4397774 ]])

In [11]:
# generating random using torch
torch.rand(2,2)

tensor([[0.4057, 0.0180],
        [0.2231, 0.0552]])

### 3. Seeds for Reproducibility

In [12]:
#numpy Seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [13]:
# Seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [16]:
# No Seed
np.random.rand(2,2) # no seed we are getting different array

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [18]:
# Torch Seed

torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [19]:
# Torch Seed

torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [20]:
# No Seed
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

### 4. Numpy & Torch Bridge

#### Numpy to Torch

In [23]:
# Numpy array
np_array = np.ones((2,2))

In [24]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [25]:
print(type(np_array))

<class 'numpy.ndarray'>


In [26]:
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

In [27]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [28]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [29]:
# Data Types matter in PyTorch

new_array= np.ones((2,2),dtype=np.int8)
torch.from_numpy(new_array)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

#### The conversion supports

- double
- float
- int64,int32,uint8

In [30]:
# Data Type int64

new_array= np.ones((2,2),dtype=np.int64)
torch.from_numpy(new_array)

tensor([[1, 1],
        [1, 1]])

In [31]:
# Data Type int32
new_array= np.ones((2,2),dtype=np.int32)
torch.from_numpy(new_array)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [32]:
# Data Type uint8
new_array= np.ones((2,2),dtype=np.uint8)
torch.from_numpy(new_array)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [33]:
# Data Type float
new_array= np.ones((2,2),dtype=np.float64)
torch.from_numpy(new_array)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [34]:
# Data Type double
new_array= np.ones((2,2),dtype=np.double)
torch.from_numpy(new_array)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

#### Summery

These things doesn't matter much now. But later when we see error messages that require these particular tensor types , we can refer to this guide . 

| Numpy Array Type    | Torch Tensor Type     
| ------------- |:-------------:
| int64         | LongTensor
| int32         | IntegerTensor  
| uint8         | ByteTensor  
| float64       | DoubleTensor  
| float32       | FloatTensor   
| double        | DoubleTensor  

#### Torch to Numpy

In [35]:
torch_tensor = torch.ones(2,2)

In [36]:
type(torch_tensor)

torch.Tensor

In [39]:
torch_to_numpy = torch_tensor.numpy()

In [40]:
type(torch_to_numpy)

numpy.ndarray

### 5. Tensor Operations

#### Resizing Tensor

In [42]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [44]:
a.size()

torch.Size([2, 2])

In [46]:
a.view(4)

tensor([1., 1., 1., 1.])

In [47]:
a.view(4).size()

torch.Size([4])

### Element Wise Addition 

In [57]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [58]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [59]:
# Element wise addition
c = a+b
c

tensor([[2., 2.],
        [2., 2.]])

In [60]:
# Element wise addition
c = torch.add(a,b)
c

tensor([[2., 2.],
        [2., 2.]])

In [61]:
# In-Place addition

print("Old c Tensor ")
print(c)

c.add_(a)

print('_'*60)
print("New c Tensor ")
print(c)

Old c Tensor 
tensor([[2., 2.],
        [2., 2.]])
____________________________________________________________
New c Tensor 
tensor([[3., 3.],
        [3., 3.]])


### Element Wise Subtraction

In [63]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [64]:
a-b

tensor([[0., 0.],
        [0., 0.]])

In [65]:
# not in-place
a.sub(b)

tensor([[0., 0.],
        [0., 0.]])

In [66]:
a

tensor([[1., 1.],
        [1., 1.]])

In [67]:
# inplace
a.sub_(b)

tensor([[0., 0.],
        [0., 0.]])

In [68]:
a

tensor([[0., 0.],
        [0., 0.]])

### Element Wise Multiplication

In [76]:


a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [79]:
b = torch.zeros(2,2)
b

tensor([[0., 0.],
        [0., 0.]])

In [80]:
a*b

tensor([[0., 0.],
        [0., 0.]])

In [81]:
# Not in place
torch.mul(a,b)

tensor([[0., 0.],
        [0., 0.]])

In [82]:
# In-place
a.mul_(b)

tensor([[0., 0.],
        [0., 0.]])

### Element Wise Division

In [83]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

In [84]:
b/a

tensor([[0., 0.],
        [0., 0.]])

In [85]:
# In place
b.div_(a)



tensor([[0., 0.],
        [0., 0.]])

### Tensor Mean

* 1+2+3+4+5+6+7+8+9+10 = 55
* mean = 55/10 =5.5

In [89]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [91]:
a.mean(dim=0) #only one dimension

tensor(5.5000)

In [92]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
a.size()

torch.Size([2, 10])

In [94]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

### Tensor Standard Deviation 

In [95]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.std(dim=0)

tensor(3.0277)