# PyTorch Fundamentals : Variables and Gradients

### 1.Variables

* A variable wraps a Tensor.
* Allows accumulation of gradients .


In [1]:
import torch
from torch.autograd import Variable

In [2]:
a = Variable(torch.ones(2,2),requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
# not a variable
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [4]:
# Behaves simillarly to tensors
b = Variable(torch.ones(2,2),requires_grad=True)
print(a+b)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


In [5]:
print(torch.add(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


In [6]:
print(a*b)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)


In [7]:
print(torch.mul(a,b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)


## Gradients

*** What exactly is require to use requires_grad?***
- Allows calculation of gradients w.r.t the variables.
- Define original equation
- Substitute equation with x values 
- Reduce the scalar output, *o* through mean
- Calculate gradients with o.backward()
- Then access gradients of the x variable through x.grad()

In [28]:
# setting x = 1

x = Variable(torch.ones(2), requires_grad=True)
print(x)

tensor([1., 1.], requires_grad=True)


In [29]:
# solving a equation

y = 5 * (x +1) ** 2
print(y)

tensor([20., 20.], grad_fn=<MulBackward>)


In [30]:
# Backward should be called only on a scalar  
o = (1/2) * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward>)

In [31]:
# backwards calculates the median
# backwards should be called only oa a scalar

o.backward()

In [33]:
# accessing the gradient
# gradient with respect to x 
x.grad

tensor([10., 10.])