# LSTMCell Using Numpy

In [2]:
import numpy as np

In [3]:
x = np.array([[1., 1., 1.]])
c = 0.1 * np.asarray([[0, 1]])
h = 0.1 * np.asarray([[2, 3]])

In [4]:
c

array([[0. , 0.1]])

In [5]:
h

array([[0.2, 0.3]])

In [6]:
x

array([[1., 1., 1.]])

In [7]:
num_units = 2

In [8]:
args = np.concatenate((x,h), axis=1)
print(args)


[[1.  1.  1.  0.2 0.3]]


In [9]:
out_size = 4 * num_units
proj_size = args.shape[-1]
print(out_size)
print(proj_size)

8
5


In [10]:
weights = np.ones([proj_size, out_size]) * 0.5

In [11]:
print(weights)

[[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]]


In [12]:
out = np.matmul(args, weights)
print(out)

[[1.75 1.75 1.75 1.75 1.75 1.75 1.75 1.75]]


In [13]:
bias = np.ones([out_size]) * 0.5
print(bias)

[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


In [14]:
concat = out + bias
print(concat)

[[2.25 2.25 2.25 2.25 2.25 2.25 2.25 2.25]]


In [15]:
i, j, f, o = np.split(concat, 4, 1)
print(i)
print(j)
print(f)
print(o)

[[2.25 2.25]]
[[2.25 2.25]]
[[2.25 2.25]]
[[2.25 2.25]]


In [16]:
g = np.tanh(j)
print(g)

[[0.97802611 0.97802611]]


![LSTM](img/lstm13.png)

#### Step1 - Calculate forget gate

In [17]:
def sigmoid_array(x):
    return 1 / (1 + np.exp(-x))

In [18]:
forget_bias = 1.0

In [19]:
sigmoid_f = sigmoid_array(f + forget_bias)
print(sigmoid_f)

[[0.96267311 0.96267311]]


![LSTM](img/lstm14.png)

#### Step2 - Calculate C

In [22]:
sigmoid_array(i) * g

array([[0.88477185, 0.88477185]])

In [23]:
new_c = c * sigmoid_f + sigmoid_array(i) * g
print(new_c)

[[0.88477185 0.98103916]]


![LSTM](img/lstm15.png)

#### Step3 - Calculate h

In [24]:
new_h = np.tanh(new_c) * sigmoid_array(o)
print(new_h)

[[0.64121796 0.68166811]]


In [25]:
print(new_h)
print(new_c)

[[0.64121796 0.68166811]]
[[0.88477185 0.98103916]]
